### ISSUE TITLE
lab4: spotlight api still broken? 

### ISSUE THREAD

**Issue by samuelstroschein** [cltl/text-mining-ba#2] opened 2021-03-05 11:06 UTC
Hey,
you closed the old issue. I believe when someone replies to a closed issue, notifications are disabled. Therefore, I opened a new issue. 

@piekvossen are you sure that the problem is fixed? Your given endpoint still returns all entity\_mentions.spotlight\_links to be `NIL` in my case. That is problematic because the `evaluate_entity_linking` function throws a division by zero error if a list of NIL/NONE/Null values are passed to calculate precision, recall and f1.   
  
I reran the updated lab4b.2. Also there, the spotlight\_links are NIL with the deviation that some values are not null but only a minority. I used the following code to inspect the entity values:  
```python
for article in processed_both:
    for entity in article.entity_mentions:
        print(entity.spotlight_link)
```

Can you confirm if my approach is correct/or that the API problem is still not fixed?

_Originally posted by @samuelstroschein in https://github.com/cltl/ba-text-mining/issues/1#issuecomment-790778803_

**Comment by lgelderloos** [comment] 2021-03-05 14:18
Hi Samuel, just letting you&Piek know I'm working on it. Indeed looks like the API is down - trying to find an alternative.

**Comment by lgelderloos** [comment] 2021-03-05 14:37
@samuelstroschein unfrtunately I can't reproduce the issue - looks like AIDA is unavailable rather than Spotlight. tbc

**Comment by lgelderloos** [comment] 2021-03-05 14:50
@samuelstroschein @piekvossen could you check if AIDA works for you? I can't get the web I suspect it has to do with th

**Comment by lgelderloos** [comment] 2021-03-05 14:56
Looks like indeed the AIDA web service is down. AIDA is now Ambiverse NLU. https://github.com/ambiverse-nlu/ I will figure out if it still has a similar HTTP service and adjust the notebook.

**Comment by samuelstroschein** [comment] 2021-03-05 15:00
@lgelderloos I just ran the updated code from notebook lab 4b.2. After running the `processed_both=spotlight_disambiguate(processed_aida, spotlight_disambiguation_url)` function I expected  links in the entity mentions for spotlight in processed_both. But every spotlight_link is None. Maybe my approach is just wrong. I attached the notebook which shows that the values are None (I hope the cell output gets saved). 

[Lab4b.2-Entity-linking-tools.ipynb.zip](https://github.com/cltl/ba-text-mining/files/6091303/Lab4b.2-Entity-linking-tools.ipynb.zip)

**Comment by lgelderloos** [comment] 2021-03-05 15:02
@samuelstroschein I'm trying to work thought this one step at a time; did you also rerun the Aida-part of the notebook? Does the http service work for you?

**Comment by samuelstroschein** [comment] 2021-03-05 16:57
If I remember correctly, that did work, or at least the links were not null/none.

**Comment by piekvossen** [comment] 2021-03-07 07:02
The new DBP Spotlight server uses a different the API. It now requires a JSON as input instead of an XML. There is now a new function that works. AIDA did work for me earlier this week but the server seems to be down now. Great timing. I hope it gets back soon

**Comment by piekvossen** [comment] 2021-03-07 07:03
Please test the new DBP Spotlight function with JSON format. If this is OK, we can remove the old function and adapt the assignment. If AIDA does not come back, we need to drop that part this week.

**Comment by samuelstroschein** [comment] 2021-03-07 08:14
Seems to work. Still some NIL values but I assume that's on purpose.

**Comment by lgelderloos** [comment] 2021-03-07 13:37
Thanks Piek and Samuel. I've done the following:
- tested Piek's JSON function Spotlight in 4.b2, confirmed it works for me too
- adjusted the Spotlight code in 4b.4 so it works with the new API
- took out the xml functions from 4b.2 as they are obsolete.
Am now running the code for the assignment only using the new Spotlight JSON function (not aida as the webserver is down), checking for inconsistencies with the questions. Will close this issue after that is done.

Regarding AIDA, I opened a new issue.

**Comment by samuelstroschein** [comment] 2021-03-07 14:27
@lgelderloos Thanks for the reply. I assume that issue can be closed then.

**Comment by piekvossen** [comment] 2021-03-13 09:29
solved

**Closed as completed by piekvossen** 2021-03-13 09:29 UTC
